#%RAML 1.0 NamedExample        
personNameGet1:  
  -
    personNameElementId: "d75ffe21-e3a3-4036-b7e4-ba0a73ed7877"
    surName:  "Kirk"
    restOfName: "Sullivan"
    startDate: "2016-01-01"
    endDate: "2018-01-01"    
  -
    personNameElementId: "d75ffe21-e3a3-4036-b7e4-ba0a73ed7877"
    surName:  "Kirk"
    restOfName: "Kirkey"
    startDate: "2018-01-01"
    endDate: "2019-01-01"    
  