#%RAML 1.0 NamedExample        
personSubjectCreate1:  
  mediaId: ""
  description: "A guy from Michigan"
  languageCode: "ENU"
  personNameElement:
    -
      surName:  "Kirk"
      restOfName: "Sullivan"
      startDate: "2016-01-01"
      endDate: "2018-01-01"    
    -
      surName:  "Kirk"
      restOfName: "Sullivan"
      endDate: "2016-01-01"    

