#%RAML 1.0 NamedExample        
personSubjectGet1:  
-
  personSubjectId: "d75ffe21-e3a3-4036-b7e4-ba0a73ed7877"
  mediaId: "75ffe21-e3a3-4036-b7e4-ba0a73ed7877"
  contentURL: "https://something"
  description: "A guy from Michigan"
  status: "active"
  datetimeCreated: "2012-04-23T18:25:43.511Z"
  datetimeModified: "2012-04-23T18:25:43.511Z"
  languageCode: "ENU"
  languageName: "English" 
  personNameElement:
    -
      personNameElementId:  "f75ffe21-e3a3-4036-b7e4-ba0a73ed7877"
      surName:  "Bob"
      restOfName: "Franklin"
      startDate: "2016-01-01"
      endDate: "2018-01-01"    
    -
      personNameElementId:  "f75ffe21-e3a3-4036-b7e4-ba0a73ed7878"
      surName:  "Bob"
      restOfName: "Franklins"
      startDate: "2014-01-01"
      endDate: "2016-01-01"    
-
  personSubjectId: "e75ffe21-e3a3-4036-b7e4-ba0a73ed7877"
  description: "A guy from Ohio"
  status: "active"
  datetimeCreated: "2012-04-23T18:25:43.511Z"
  datetimeModified: "2012-04-23T18:25:43.511Z"
  languageCode: "ENU"
  languageName: "English" 
  personNameElement:
    -
      personNameElementId:  "f75ffe21-e3a3-4036-b7e4-ba0a73ed7877"
      surName:  "Bob"
      restOfName: "Franklin"
      startDate: "2016-01-01"
      endDate: "2018-01-01"    
    -
      personNameElementId:  "f75ffe21-e3a3-4036-b7e4-ba0a73ed7878"
      surName:  "Bob"
      restOfName: "Franklins"
      startDate: "2014-01-01"
      endDate: "2016-01-01"    

