#%RAML 1.0 DocumentationItem
title: personSubjectsapi
content: |
  *PERSON SUBJECT SERVICE* enables the caller to get search definitions.
  There a number of query parameters for GET calls, either doing a general search with query parameters like language, fromPublishedDate, toPublishedDate, gender, genderType, personNameElement,  storyPersonSubject , evidencePersonSubject and factPersonSubject or doing a specific search by newsSearchId