#%RAML 1.0 Trait
responses:
  400:
    body:
     application/json:
      example:
        {
          statusCode: 101,
          message: "Please correct the request message and try again."
        }
  401:
    body:
     application/json:
      example:
        {
          statusCode: 101,
          message: "Please correct the request message and try again."
        }
  404:
    body:
     application/json:
      example:
        {
          statusCode: 101,
          message: "Please correct the request message and try again."
        }
  405:
    body:
     application/json:
      example:
        {
          statusCode: 101,
          message: "Please correct the request message and try again."
        }      
  406:
    body:
     application/json:
      example:
        {
          statusCode: 101,
          message: "Please correct the request message and try again."
        }
  415:
    body:
     application/json:
      example:
        {
          statusCode: 101,
          message: "Please correct the request message and try again."
        }
  500:
    body:
      application/json:
        example:
         {
          statusCode: 101,
          message: "Please correct the request message and try again."
         }
  503:
    body:
      application/json:
        example:
         {
          statusCode: 101,
          message: "Please correct the request message and try again."
         }