#%RAML 1.0 Trait
responses:
  201:
    body:
      application/json:
        type: object
        properties:
          id: string
        example:
          {
            id: "asdh2r89sdhied438893fa24a0789a99"
          }
